import { useEffect, useMemo, useState } from "react";
import { LanguageContext } from "./languageContext";

const translations = {
  en: {
    collections: "Collections",
    aboutUs: "About us",
    contacts: "Contacts",
    wishlist: "Wishlist",
    bag: "Bag",
    logIn: "Log in",
    close: "Close",
    closeBag: "Close bag",
    account: "Account",
    subscribeTitle: "Subscribe & save",
    subscribeText:
      "Subscribe to our email newsletter and receive the best offers and discounts",
    emailPlaceholder: "Email",
    subscribeButton: "Subscribe",
    home: "Home",
    products: "Products",
    favorites: "Favorites",
    bagEmpty: "Your bag is empty.",
    soldOut: "Sold out",
    inStock: "In stock",
    shippingKit: "Shipping kit",
    serviceOption: "Service option",
    inStore: "In-store",
    color: "Color",
    size: "Size",
    oneSize: "One size",
    decreaseQuantity: "Decrease quantity",
    increaseQuantity: "Increase quantity",
    removeItem: "Remove item",
    checkout: "Check out",
    warranty: "2 Year Warranty",
    highQuality: "High Quality",
    fastDelivery: "Fast Delivery",
    return90Days: "90-Day Return",
    bestSellers: "Best sellers",
    seeAll: "See all",
    seeAllBestSellers: "See all best sellers",
    categories: "Categories",
    heroTitleLine1: "Discover",
    heroTitleLine2: "Timeless",
    heroTitleLine3: "Elegance",
    heroTitleDesktop: "Discover Timeless Elegance",
    previous: "Previous",
    next: "Next",
    noItemsAvailable: "No items available at the moment.",
    newCollection: "New collection",
    newCollectionLine1: "New",
    newCollectionLine2: "collection",
    shopNow: "Shop now",
    shopNewCollection: "Shop new collection",
    personalizedJewellery: "Personalized jewellery",
    personalizedLine1: "Personalized",
    personalizedLine2: "Jewellery",
    shopPersonalizedJewellery: "Shop personalized jewellery",
    filter: "Filter",
    closeFilter: "Close filter",
    material: "Material",
    price: "Price",
    appearance: "Appearance",
    gemstones: "Gemstones",
    to: "to",
    sortBy: "Sort by:",
    closeSort: "Close sort",
    sortPriceHighToLow: "Price, high to low",
    sortPriceLowToHigh: "Price, low to high",
    sortBestSelling: "Best selling",
    sortDateOldToNew: "Date, old to new",
    sortDateNewToOld: "Date, new to old",
    selectCategory: "Select category",
    testimonialsTitle: "What people\nsay about us",
    add: "Add",
    remove: "Remove",
    toCart: "to cart",
    toFavorites: "to favorites",
    fromFavorites: "from favorites",
    toBag: "to bag",
    open: "Open",
    hover: "hover",
    productImage: "Jewelry product image",
    aboutStudioText:
      "Every piece of our jewelry is created to capture a feeling — love, beauty, and timeless elegance. Crafted with exquisite detail and the finest materials, each design is meant to be cherished. Here, luxury becomes part of your story.",
    aboutStudioImageAlt: "About our studio",
    studioLogoAlt: "Studio logo",
    addToBag: "Add to bag",
    clearAll: "Clear all",
    pagination: "Pagination",
    previousPage: "Previous page",
    nextPage: "Next page",
    page: "Page",
    umStudioLogo: "UM Studio",
    subscribeAndSave: "Subscribe & save",
    subscribeBannerText:
      "Subscribe to our email newsletter and receive the best offers and discounts",
    subscribe: "Subscribe",
    subscribeBannerImageAlt: "Subscribe banner",
    rings: "Rings",
    necklaces: "Necklaces",
    bracelets: "Bracelets",
    earrings: "Earrings",
    personal: "Personal",

    withGem: "With gemstone",
    withoutGem: "Without gemstone",
    rough: "Rough",
    smoothSurface: "Smooth surface",

    kristolas: "Crystal",
    cirkonis: "Zircon",
    deimantas: "Diamond",
    perlas: "Pearl",

    silver: "Silver",
    gold: "Gold",
    softBlue: "Soft blue",
    softGreen: "Soft green",

    loading: "Loading...",
    noProductsFound: "No products found.",
    showing: "Showing",
    of: "of",

    phone: "Phone",
    name: "Name",
    enterYourName: "Enter your name",
    enterYourEmail: "Enter your email",
    phoneNumber: "Phone number",
    enterYourPhoneNumber: "Enter your phone number",
    yourMessage: "Your message",
    enterMessage: "Enter message",
    sendMessage: "Send message",
    yourMessageSentSuccessfully: "Your message sent successfully",
    messageSent: "Message sent",
    pleaseFillInThisField: "Please fill in this field.",
    enterValidEmailAddress: "Enter a valid email address.",

    myFavourites: "My favourites",
    noFavouriteItemsYet: "You don't have any favourite items yet.",

    hidePassword: "Hide password",
    showPassword: "Show password",
    thisFieldIsRequired: "This field is required.",
    passwordsDoNotMatch: "Passwords do not match.",
    somethingWentWrong: "Something went wrong.",
    signIn: "Sign in",
    createAccount: "Create an account",
    firstName: "First name",
    lastName: "Last name",
    emailAddress: "Email address",
    password: "Password",
    confirmPassword: "Confirm password",
    pleaseWait: "Please wait...",
    forgotPassword: "Forgot password?",

    pageNotFound: "Page not found",
    thisPageDoesNotExist: "This page does not exist.",
    notFoundText:
      "The page you are looking for may have been moved, removed, or the link may be incorrect.",
    backToHome: "Back to home",
    viewCollections: "View collections",
    discoverJewelryThatStays:
      "Discover jewelry that becomes part of your story.",
    notFoundSideText:
      "Explore our collections and find timeless pieces designed to be worn, gifted, and remembered.",

    bestSellersIntroDescription:
      "Every piece of our jewelry is created to capture a feeling — love, beauty, and timeless elegance. Crafted with exquisite detail and the finest materials, each design is meant to be cherished.",
    personalizedJewelry: "Personalized jewelry",

    ourSalons: "Our salons",
    salon: "salon",
    workingHours: "Mon–Sun — 10:00–20:00",

    exploreOurProducts: "Explore our products",
    personalizedProducts: "Personalized products",

    orderHistory: "Order history",
    profile: "Profile",
    logOut: "Log out",

    changePassword: "Change password",
    back: "Back",
    currentPassword: "Current password",
    newPassword: "New password",
    repeatNewPassword: "Repeat new password",
    saving: "Saving...",
    save: "Save",
    passwordUpdatedSuccessfully: "Password updated successfully.",
    passwordMustBeAtLeast: "Password must be at least",
    characters: "characters",

    openOrder: "Open order",
    more: "more",
    orderNo: "Order no.",

    loadingOrders: "Loading orders...",
    noOrdersYet: "No orders yet.",
    failedToLoadOrders: "Failed to load orders.",
    product: "Product",
    pickup: "Pickup",
    omniva: "Omniva",
    lpExpress: "LP Express",
    notAvailable: "-",

    orderDate: "Order date",
    deliveryTo: "Delivery to",
    billingAddress: "Billing address",
    service: "Service",
    delivery: "Delivery",
    carrier: "Carrier",
    deliveryPrice: "Delivery price",
    total: "Total",
    shippingKitWithPrice: "Shipping kit (+15€)",

    requiredShort: "Required.",
    savedSuccessfully: "Saved successfully.",
    enterYourFirstName: "Enter your first name",
    enterYourLastName: "Enter your last name",
    change: "Change",

    pleaseChooseServiceOption: "Please choose service option.",
    productNotFound: "Product not found.",
    invalidProductUrl: "Invalid product URL.",
    backToCollections: "Back to Collections",

    softYellow: "Soft yellow",
    ninetyDayReturn: "90 - Day Return",
    selectedVariantSoldOut: "Selected variant is sold out",
    removeFromWishlist: "Remove from wishlist",
    addToWishlist: "Add to wishlist",
    dimensionsAndDetails: "Dimensions & details",
    personalJewelleryHowItWorks: "Personal jewellery - How it works",
    quantity: "Quantity",

    youMayAlsoLike: {
      titleLine1: "You may",
      titleLine2: "also like",
      seeAll: "See all",
      seeAllAriaLabel: "See all products",
    },
  },
  lt: {
    collections: "Kolekcijos",
    aboutUs: "Apie mus",
    contacts: "Kontaktai",
    wishlist: "Patikusios",
    bag: "Krepšelis",
    logIn: "Prisijungti",
    close: "Uždaryti",
    closeBag: "Uždaryti krepšelį",
    account: "Paskyra",
    subscribeTitle: "Prenumeruokite ir sutaupykite",
    subscribeText:
      "Prenumeruokite mūsų naujienlaiškį el. paštu ir gaukite geriausius pasiūlymus bei nuolaidas",
    emailPlaceholder: "El. paštas",
    subscribeButton: "Prenumeruoti",
    home: "Pagrindinis",
    products: "Produktai",
    favorites: "Patikusios",
    bagEmpty: "Jūsų krepšelis tuščias.",
    soldOut: "Išparduota",
    inStock: "Liko",
    shippingKit: "Siuntimo rinkinys",
    serviceOption: "Paslaugos pasirinkimas",
    inStore: "Salone",
    color: "Spalva",
    size: "Dydis",
    oneSize: "Vienas dydis",
    decreaseQuantity: "Sumažinti kiekį",
    increaseQuantity: "Padidinti kiekį",
    removeItem: "Pašalinti prekę",
    checkout: "Apmokėti",
    warranty: "2 metų garantija",
    highQuality: "Aukšta kokybė",
    fastDelivery: "Greitas pristatymas",
    return90Days: "90 dienų grąžinimas",
    bestSellers: "Perkamiausi",
    seeAll: "Žiūrėti visus",
    seeAllBestSellers: "Žiūrėti visus perkamiausius",
    categories: "Kategorijos",
    heroTitleLine1: "Atraskite",
    heroTitleLine2: "Nesenstančią",
    heroTitleLine3: "Eleganciją",
    heroTitleDesktop: "Atraskite nesenstančią eleganciją",
    previous: "Ankstesnis",
    next: "Kitas",
    noItemsAvailable: "Šiuo metu prekių nėra.",
    newCollection: "Nauja kolekcija",
    newCollectionLine1: "Nauja",
    newCollectionLine2: "kolekcija",
    shopNow: "Pirkti",
    shopNewCollection: "Pirkti naują kolekciją",
    personalizedJewellery: "Personalizuoti papuošalai",
    personalizedLine1: "Personalizuoti",
    personalizedLine2: "papuošalai",
    shopPersonalizedJewellery: "Pirkti personalizuotus papuošalus",
    filter: "Filtrai",
    closeFilter: "Uždaryti filtrus",
    material: "Medžiaga",
    price: "Kaina",
    appearance: "Išvaizda",
    gemstones: "Brangakmeniai",
    to: "iki",
    sortBy: "Rūšiuoti pagal:",
    closeSort: "Uždaryti rūšiavimą",
    sortPriceHighToLow: "Kaina, nuo didžiausios",
    sortPriceLowToHigh: "Kaina, nuo mažiausios",
    sortBestSelling: "Perkamiausi",
    sortDateOldToNew: "Data, nuo seniausių",
    sortDateNewToOld: "Data, nuo naujausių",
    selectCategory: "Pasirinkti kategoriją",
    testimonialsTitle: "Ką žmonės\nsako apie mus",
    add: "Pridėti",
    remove: "Pašalinti",
    toCart: "į krepšelį",
    toFavorites: "į patikusias",
    fromFavorites: "iš patikusių",
    toBag: "į krepšelį",
    open: "Atidaryti",
    hover: "užvedus",
    productImage: "Papuošalo nuotrauka",
    aboutStudioText:
      "Kiekvienas mūsų papuošalas kuriamas tam, kad perteiktų jausmą — meilę, grožį ir nesenstančią eleganciją. Kruopščiai pagamintas iš aukščiausios kokybės medžiagų, kiekvienas dizainas skirtas būti branginamas. Čia prabanga tampa jūsų istorijos dalimi.",
    aboutStudioImageAlt: "Apie mūsų studiją",
    studioLogoAlt: "Studijos logotipas",
    addToBag: "Į krepšelį",
    clearAll: "Išvalyti viską",
    pagination: "Puslapiavimas",
    previousPage: "Ankstesnis puslapis",
    nextPage: "Kitas puslapis",
    page: "Puslapis",
    umStudioLogo: "UM Studio",
    subscribeAndSave: "Prenumeruokite ir sutaupykite",
    subscribeBannerText:
      "Prenumeruokite mūsų naujienlaiškį el. paštu ir gaukite geriausius pasiūlymus bei nuolaidas",
    subscribe: "Prenumeruoti",
    subscribeBannerImageAlt: "Prenumeratos reklamjuostė",
    rings: "Žiedai",
    necklaces: "Kaklo papuošalai",
    bracelets: "Apyrankės",
    earrings: "Auskarai",
    personal: "Personalizuoti",

    withGem: "Su brangakmeniu",
    withoutGem: "Be brangakmenio",
    rough: "Grublėtas",
    smoothSurface: "Lygus paviršius",

    kristolas: "Kristolas",
    cirkonis: "Cirkonis",
    deimantas: "Deimantas",
    perlas: "Perlas",

    silver: "Sidabras",
    gold: "Auksas",
    softBlue: "Švelni mėlyna",
    softGreen: "Švelni žalia",

    loading: "Kraunama...",
    noProductsFound: "Produktų nerasta.",
    showing: "Rodoma",
    of: "iš",

    phone: "Telefonas",
    name: "Vardas",
    enterYourName: "Įveskite savo vardą",
    enterYourEmail: "Įveskite savo el. paštą",
    phoneNumber: "Telefono numeris",
    enterYourPhoneNumber: "Įveskite savo telefono numerį",
    yourMessage: "Jūsų žinutė",
    enterMessage: "Įveskite žinutę",
    sendMessage: "Siųsti žinutę",
    yourMessageSentSuccessfully: "Jūsų žinutė sėkmingai išsiųsta",
    messageSent: "Žinutė išsiųsta",
    pleaseFillInThisField: "Užpildykite šį lauką.",
    enterValidEmailAddress: "Įveskite galiojantį el. pašto adresą.",

    myFavourites: "Mano mėgstamiausi",
    noFavouriteItemsYet: "Dar neturite mėgstamų prekių.",

    hidePassword: "Slėpti slaptažodį",
    showPassword: "Rodyti slaptažodį",
    thisFieldIsRequired: "Šis laukas yra privalomas.",
    passwordsDoNotMatch: "Slaptažodžiai nesutampa.",
    somethingWentWrong: "Kažkas nepavyko.",
    signIn: "Prisijungti",
    createAccount: "Sukurti paskyrą",
    firstName: "Vardas",
    lastName: "Pavardė",
    emailAddress: "El. pašto adresas",
    password: "Slaptažodis",
    confirmPassword: "Patvirtinkite slaptažodį",
    pleaseWait: "Prašome palaukti...",
    forgotPassword: "Pamiršote slaptažodį?",

    pageNotFound: "Puslapis nerastas",
    thisPageDoesNotExist: "Šis puslapis neegzistuoja.",
    notFoundText:
      "Puslapis, kurio ieškote, galėjo būti perkeltas, pašalintas arba nuoroda yra neteisinga.",
    backToHome: "Grįžti į pradžią",
    viewCollections: "Peržiūrėti kolekcijas",
    discoverJewelryThatStays:
      "Atraskite papuošalus, kurie tampa jūsų istorijos dalimi.",
    notFoundSideText:
      "Peržiūrėkite mūsų kolekcijas ir raskite nesenstančius papuošalus, skirtus nešioti, dovanoti ir branginti.",

    bestSellersIntroDescription:
      "Kiekvienas mūsų papuošalas kuriamas tam, kad perteiktų jausmą — meilę, grožį ir nesenstančią eleganciją. Kruopščiai pagamintas iš aukščiausios kokybės medžiagų, kiekvienas dizainas skirtas būti branginamas.",
    personalizedJewelry: "Personalizuoti papuošalai",

    ourSalons: "Mūsų salonai",
    salon: "salonas",
    workingHours: "I–VII — 10:00–20:00",

    exploreOurProducts: "Atraskite mūsų produktus",
    personalizedProducts: "Personalizuoti produktai",

    orderHistory: "Užsakymų istorija",
    profile: "Profilis",
    logOut: "Atsijungti",

    changePassword: "Keisti slaptažodį",
    back: "Atgal",
    currentPassword: "Dabartinis slaptažodis",
    newPassword: "Naujas slaptažodis",
    repeatNewPassword: "Pakartokite naują slaptažodį",
    saving: "Saugoma...",
    save: "Išsaugoti",
    passwordUpdatedSuccessfully: "Slaptažodis sėkmingai atnaujintas.",
    passwordMustBeAtLeast: "Slaptažodis turi būti bent",
    characters: "simbolių",

    openOrder: "Atidaryti užsakymą",
    more: "daugiau",
    orderNo: "Užsakymo nr.",

    loadingOrders: "Kraunami užsakymai...",
    noOrdersYet: "Užsakymų dar nėra.",
    failedToLoadOrders: "Nepavyko užkrauti užsakymų.",
    product: "Produktas",
    pickup: "Atsiėmimas",
    omniva: "Omniva",
    lpExpress: "LP Express",
    notAvailable: "-",

    orderDate: "Užsakymo data",
    deliveryTo: "Pristatyti į",
    billingAddress: "Atsiskaitymo adresas",
    service: "Paslauga",
    delivery: "Pristatymas",
    carrier: "Vežėjas",
    deliveryPrice: "Pristatymo kaina",
    total: "Iš viso",
    shippingKitWithPrice: "Siuntimo rinkinys (+15€)",

    requiredShort: "Privaloma.",
    savedSuccessfully: "Sėkmingai išsaugota.",
    enterYourFirstName: "Įveskite savo vardą",
    enterYourLastName: "Įveskite savo pavardę",
    change: "Keisti",

    pleaseChooseServiceOption: "Pasirinkite paslaugos variantą.",
    productNotFound: "Produktas nerastas.",
    invalidProductUrl: "Neteisinga produkto nuoroda.",
    backToCollections: "Grįžti į kolekcijas",

    softYellow: "Švelni geltona",
    twoYearWarranty: "2 metų garantija",
    ninetyDayReturn: "90 dienų grąžinimas",
    selectedVariantSoldOut: "Pasirinktas variantas išparduotas",
    removeFromWishlist: "Pašalinti iš mėgstamų",
    addToWishlist: "Pridėti į mėgstamus",
    dimensionsAndDetails: "Išmatavimai ir detalės",
    personalJewelleryHowItWorks: "Personalizuoti papuošalai - kaip tai veikia",
    quantity: "Kiekis",

    youMayAlsoLike: {
      titleLine1: "Jums gali",
      titleLine2: "taip pat patikti",
      seeAll: "Žiūrėti visus",
      seeAllAriaLabel: "Žiūrėti visus produktus",
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem("lang") || "en";
  });

  useEffect(() => {
    localStorage.setItem("lang", lang);
  }, [lang]);

  const value = useMemo(() => {
    return {
      lang,
      setLang,
      t: translations[lang],
    };
  }, [lang]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
