import { useEffect, useMemo, useState } from "react";
import { LanguageContext } from "./languageContext";

const translations = {
  en: {
    thankYou: "Thank you!",
    subscriptionSuccess: "You have successfully subscribed to our newsletter.",
    collections: "Collections",
    aboutUs: "About us",
    contacts: "Contacts",
    wishlist: "Wishlist",
    bag: "Bag",
    logIn: "Log in",
    close: "Close",
    closeBag: "Close bag",
    account: "Account",
    subscribeTitle: "Subscribe & save",
    subscribeText:
      "Subscribe to our email newsletter and receive the best offers and discounts",
    emailPlaceholder: "Email",
    subscribeButton: "Subscribe",
    home: "Home",
    products: "Products",
    favorites: "Favorites",
    bagEmpty: "Your bag is empty.",
    soldOut: "Sold out",
    inStock: "In stock",
    shippingKit: "Shipping kit",
    serviceOption: "Service option",
    inStore: "In-store",
    color: "Color",
    size: "Size",
    oneSize: "One size",
    decreaseQuantity: "Decrease quantity",
    increaseQuantity: "Increase quantity",
    removeItem: "Remove item",
    checkout: "Check out",
    warranty: "2 Year Warranty",
    twoYearWarranty: "2 Year Warranty",
    highQuality: "High Quality",
    fastDelivery: "Fast Delivery",
    return90Days: "90-Day Return",
    ninetyDayReturn: "90-Day Return",
    bestSellers: "Best sellers",
    seeAll: "See all",
    seeAllBestSellers: "See all best sellers",
    categories: "Categories",
    heroTitleLine1: "Discover",
    heroTitleLine2: "Timeless",
    heroTitleLine3: "Elegance",
    heroTitleDesktop: "Discover Timeless Elegance",
    previous: "Previous",
    next: "Next",
    noItemsAvailable: "No items available at the moment.",
    newCollection: "New collection",
    newCollectionLine1: "New",
    newCollectionLine2: "collection",
    shopNow: "Shop now",
    shopNewCollection: "Shop new collection",
    personalizedJewellery: "Personalized jewellery",
    personalizedLine1: "Personalized",
    personalizedLine2: "Jewellery",
    shopPersonalizedJewellery: "Shop personalized jewellery",
    filter: "Filter",
    closeFilter: "Close filter",
    material: "Material",
    price: "Price",
    appearance: "Appearance",
    gemstones: "Gemstones",
    to: "to",
    sortBy: "Sort by:",
    closeSort: "Close sort",
    sortPriceHighToLow: "Price, high to low",
    sortPriceLowToHigh: "Price, low to high",
    sortBestSelling: "Best selling",
    sortDateOldToNew: "Date, old to new",
    sortDateNewToOld: "Date, new to old",
    selectCategory: "Select category",
    testimonialsTitle: "What people\nsay about us",
    testimonials: {
      "jessica-shy": "Minimal yet full of character. Looks luxurious, but feels light as air on the skin.",
      "tomas-narkevicius": "Modern design without excess. I wear them often – they always get noticed.",
      "angelou": "Very elegant jewelry. Perfectly complements even the simplest outfit.",
      "fc-baseball": "Stylish, high-quality, and distinctive. A great choice for gifting or yourself.",
      "donatas-montvydas": "Jewelry that works for both stage and everyday life.",
      "monika-liu": "Subtle, aesthetic, and very pleasant. You can feel the handcrafted work and attention to detail.",
    },
    productNames: {
      // Static data (bestSellers.js) - with quotes and lowercase
      '"Earth" ring': '„Žemė" žiedas',
      '"Cut" ring': '„Cut" žiedas',
      '"Dot" necklace': '„Dot" vėrinys',
      '"Echo" rings': '„Echo" žiedai',
      '"Fold" ring': '„Fold" žiedas',
      '"Fluid" ring': '„Fluid" žiedas',
      '"Still" ring': '„Still" žiedas',
      '"Um" ring': '„Um" žiedas',
      '"Pure" earrings': '„Pure" auskarai',
      '"Bond" bracelet': '„Bond" apyrankė',
      // Database products - Title Case
      "Fluid Ring": "„Fluid" žiedas",
      "Still Ring": "„Still" žiedas",
      "Fold Ring": "„Fold" žiedas",
      "Um Ring": "„Um" žiedas",
      "Earth Ring": "„Žemė" žiedas",
      "Cut Ring": "„Cut" žiedas",
      "Dot Necklace": "„Dot" vėrinys",
      "Echo Rings": "„Echo" žiedai",
      "Pure Earrings": "„Pure" auskarai",
      "Bond Bracelet": "„Bond" apyrankė",
    },
    add: "Add",
    remove: "Remove",
    toCart: "to cart",
    toFavorites: "to favorites",
    fromFavorites: "from favorites",
    toBag: "to bag",
    open: "Open",
    hover: "hover",
    productImage: "Jewelry product image",
    aboutStudioText:
      "Every piece of our jewelry is created to capture a feeling — love, beauty, and timeless elegance. Crafted with exquisite detail and the finest materials, each design is meant to be cherished. Here, luxury becomes part of your story.",
    aboutStudioImageAlt: "About our studio",
    studioLogoAlt: "Studio logo",
    addToBag: "Add to bag",
    clearAll: "Clear all",
    pagination: "Pagination",
    previousPage: "Previous page",
    nextPage: "Next page",
    page: "Page",
    umStudioLogo: "UM Studio",
    subscribeAndSave: "Subscribe & save",
    subscribeBannerText:
      "Subscribe to our email newsletter and receive the best offers and discounts",
    subscribe: "Subscribe",
    subscribeBannerImageAlt: "Subscribe banner",
    rings: "Rings",
    necklaces: "Necklaces",
    bracelets: "Bracelets",
    earrings: "Earrings",
    personal: "Personal",

    withGem: "With gemstone",
    withoutGem: "Without gemstone",
    rough: "Rough",
    smoothSurface: "Smooth surface",

    kristolas: "Crystal",
    cirkonis: "Zircon",
    deimantas: "Diamond",
    perlas: "Pearl",

    silver: "Silver",
    gold: "Gold",
    softBlue: "Soft blue",
    softGreen: "Soft green",
    softYellow: "Soft yellow",

    loading: "Loading...",
    noProductsFound: "No products found.",
    showing: "Showing",
    of: "of",

    phone: "Phone",
    name: "Name",
    enterYourName: "Enter your name",
    enterYourEmail: "Enter your email",
    phoneNumber: "Phone number",
    enterYourPhoneNumber: "Enter your phone number",
    yourMessage: "Your message",
    enterMessage: "Enter message",
    sendMessage: "Send message",
    yourMessageSentSuccessfully: "Your message sent successfully",
    messageSent: "Message sent",
    pleaseFillInThisField: "Please fill in this field.",
    enterValidEmailAddress: "Enter a valid email address.",

    myFavourites: "My favourites",
    noFavouriteItemsYet: "You don't have any favourite items yet.",

    hidePassword: "Hide password",
    showPassword: "Show password",
    thisFieldIsRequired: "This field is required.",
    passwordsDoNotMatch: "Passwords do not match.",
    somethingWentWrong: "Something went wrong.",
    signIn: "Sign in",
    createAccount: "Create an account",
    invalidCredentials: "Invalid email address or password.",
    emailAlreadyInUse: "A user with this email address already exists.",
    pleaseWait: "Please wait...",
    firstName: "First name",
    lastName: "Last name",
    emailAddress: "Email address",
    password: "Password",
    confirmPassword: "Confirm password",
    forgotPassword: "Forgot password?",

    pageNotFound: "Page not found",
    thisPageDoesNotExist: "This page does not exist.",
    notFoundText:
      "The page you are looking for may have been moved, removed, or the link may be incorrect.",
    backToHome: "Back to home",
    viewCollections: "View collections",
    discoverJewelryThatStays:
      "Discover jewelry that becomes part of your story.",
    notFoundSideText:
      "Explore our collections and find timeless pieces designed to be worn, gifted, and remembered.",

    bestSellersIntroDescription:
      "Every piece of our jewelry is created to capture a feeling — love, beauty, and timeless elegance. Crafted with exquisite detail and the finest materials, each design is meant to be cherished.",
    personalizedJewelry: "Personalized jewelry",

    ourSalons: "Our salons",
    salon: "salon",
    workingHours: "Mon–Sun — 10:00–20:00",

    exploreOurProducts: "Explore our products",
    personalizedProducts: "Personalized products",

    orderHistory: "Order history",
    profile: "Profile",
    logOut: "Log out",

    changePassword: "Change password",
    back: "Back",
    currentPassword: "Current password",
    newPassword: "New password",
    repeatNewPassword: "Repeat new password",
    saving: "Saving...",
    save: "Save",
    passwordUpdatedSuccessfully: "Password updated successfully.",
    passwordMustBeAtLeast: "Password must be at least",
    characters: "characters",

    openOrder: "Open order",
    more: "more",
    orderNo: "Order no.",

    loadingOrders: "Loading orders...",
    noOrdersYet: "No orders yet.",
    failedToLoadOrders: "Failed to load orders.",
    pickup: "Pickup",
    omniva: "Omniva",
    lpExpress: "LP Express",
    notAvailable: "-",

    orderDate: "Order date",
    deliveryTo: "Delivery to",
    billingAddress: "Billing address",
    service: "Service",
    delivery: "Delivery",
    carrier: "Carrier",
    deliveryPrice: "Delivery price",
    total: "Total",
    shippingKitWithPrice: "Shipping kit (+15€)",

    requiredShort: "Required.",
    savedSuccessfully: "Saved successfully.",
    enterYourFirstName: "Enter your first name",
    enterYourLastName: "Enter your last name",
    change: "Change",

    pleaseChooseServiceOption: "Please choose service option.",
    productNotFound: "Product not found.",
    invalidProductUrl: "Invalid product URL.",
    backToCollections: "Back to Collections",

    selectedVariantSoldOut: "Selected variant is sold out",
    removeFromWishlist: "Remove from wishlist",
    addToWishlist: "Add to wishlist",
    dimensionsAndDetails: "Dimensions & details",
    personalJewelleryHowItWorks: "Personal jewellery - How it works",
    quantity: "Quantity",
    orderValue: "Order value",

    pending: "Pending",
    confirmed: "Confirmed",
    shipped: "Shipped",
    completed: "Completed",
    canceled: "Canceled",

    product: {
      label: "Product",

      youMayAlsoLike: {
        titleLine1: "You may",
        titleLine2: "also like",
        seeAll: "See all",
        seeAllAriaLabel: "See all products",
      },

      detailsPanel: {
        title: "Dimensions & details",
        close: "Close",
        closeAriaLabel: "Close details",
        adjustableFromToPrefix: "adjustable from",
        adjustableFromToMiddle: "to",
        sectionTitles: {
          dimensions: "Dimensions:",
        },
        labels: {
          metal: "Metal - ",
          bandWidth: "Band width: ",
          weight: "Weight: ",
          gemstone: "Gemstone: ",
          productCode: "Product Code: ",
          chain: "Chain - ",
          totalNecklaceLength: "Total Necklace Length: ",
          height: "Height: ",
          width: "Width: ",
          size: "Size - ",
          totalBraceletLength: "Total Bracelet Length: ",
        },
        metals: {
          softYellow: "Soft yellow",
          softBlue: "Soft blue",
          softGreen: "Soft green",
          gold: "Gold",
          silver: "Silver",
        },
        defaultTexts: {
          rings:
            "This wide band ring features a textured surface inspired by organic forms, creating a subtle play of light and depth. Its bold silhouette is balanced by a refined finish, giving the piece a modern yet timeless character. Designed to be worn alone as a statement or paired with minimal jewellery, this ring adds effortless sophistication to any look.",
          bracelets:
            "This bold chain bracelet is crafted from interlinked, polished rings that create a strong yet balanced silhouette. Its smooth, rounded links catch the light beautifully, giving the piece a refined, contemporary feel. Designed to stand out on its own or pair effortlessly with other jewellery, this bracelet adds a modern statement to both everyday and elevated looks.",
          necklaces:
            "This delicate necklace features a fine chain accented by a sleek, drop-shaped pendant that falls gracefully along the neckline. Its minimalist design highlights clean lines and subtle movement, creating an elegant, elongated silhouette. Perfect for layering or wearing on its own, this piece adds a refined, modern touch to both everyday and evening looks.",
          earrings:
            "These minimalist earrings feature a softly contoured triangular form with a smooth, brushed surface that reflects light in a subtle, elegant way. Their sculptural silhouette adds a modern touch while remaining timeless and easy to style. Designed to complement both everyday looks and more refined outfits, they are a versatile addition to any jewellery collection.",
        },
      },
    },

    checkoutThankYou: {
      title: "Thank you for your purchase!",
      imageAlt: "Thank you",
      orderIdLabel: "Order ID",
      confirmationEmailLabel: "Confirmation email",
      backToShopping: "Go back shopping",
      shippingMessage:
        "Your order has been received successfully. We’ll send your order details and shipping updates to your email shortly.",
      pickupMessage:
        "Your order has been received successfully. We’ll contact you by email when it is ready for pickup at {pickupLocation}.",
      pickupLocations: {
        vilnius: "Vilnius salon",
        kaunas: "Kaunas salon",
        default: "our salon",
      },
    },

    checkoutPage: {
      processing: "Processing...",
      payNow: "Pay now",
      paymentSuccess: "Payment successful",
      backToCheckout: "Back to checkout",
      contactTitle: "Contact",
      emailLabel: "Email address",
      emailPlaceholder: "Enter your email",
      deliveryInformation: "Delivery information",
      ship: "Ship",
      pickup: "Pickup",
      orderSummary: "Order summary",
      quantityShort: "Qnty.",
      subtotal: "Subtotal",
      free: "Free",
      paymentTitle: "Payment",
      creditCard: "Credit card",
      cardNumberLabel: "Card number",
      cardNumberPlaceholder: "1234 1234 1234 1234",
      cardDateLabel: "Date",
      cardDatePlaceholder: "MM/YY",
      cardCvcLabel: "CVC",
      cardCvcPlaceholder: "CVC",
      cardOwnerNameLabel: "Card owner name, surname",
      cardOwnerNamePlaceholder: "Full name",
      bankPayment: "E. bank payment",
      chooseYourBank: "Choose your bank",
      bankRedirectText:
        "You will be redirected to your selected bank after clicking Pay now.",
      pickupTitle: "Pickup location",
      pickupDescription:
        "Select the salon where you want to pick up your order.",
      pickupLocations: {
        vilnius: "Vilnius salon",
        kaunas: "Kaunas salon",
      },
      pickupAddresses: {
        vilnius: "Kauno str. 24",
        kaunas: "Žemaičių str. 24",
      },

      pickupInfo:
        "Pickup is free. We will contact you by email after your order is placed.",
      countryRegionLabel: "Country/Region",
      countryLithuania: "Lithuania",
      addressLabel: "Address",
      apartmentLabel: "Apartment, suite, etc.",
      optionalPlaceholder: "(optional)",
      cityLabel: "City",
      postalCodeLabel: "Postal code",

      chooseDeliveryMethod: "Choose delivery method",
      lpDelivery: "LP EXPRESS delivery to home",
      omnivaDelivery: "Omniva delivery to home",

      errors: {
        enterValidEmail: "Enter a valid email.",
        firstNameRequired: "First name is required.",
        lastNameRequired: "Last name is required.",
        addressRequired: "Address is required.",
        cityRequired: "City is required.",
        postalCodeRequired: "Postal code is required.",
        phoneRequired: "Phone is required.",
        invalidCardNumber: "Invalid card number.",
        useCardDateFormat: "Use MM/YY.",
        invalidCvc: "Invalid CVC.",
        cardOwnerNameRequired: "Card owner name is required.",
        productNoLongerExists: 'Product "{productName}" no longer exists.',
        productSoldOut: 'Product "{productName}" is sold out.',
        notEnoughStock:
          'Only {stockQuantity} left for "{productName}", but your bag has {qty}.',
      },
    },

    personalized: {
      steps: {
        step1: {
          title: "Choose Jewellery",
          text: "Select your preferred piece from our collection of rings and necklaces. Choose the material — gold or silver — and the size that fits you best.",
          alt: "Choose jewellery",
        },
        step2: {
          title: "Add Your Personal Touch",
          shippingTitle: "Shipping option:",
          shippingText:
            "Complete your order and we will send you a kit to capture the print you would like engraved on your jewellery. Once ready, send it back to us and we will begin crafting your personalized piece.",
          inStoreTitle: "In-store option:",
          inStoreText:
            "Visit our store and we will take the print on-site. After that, simply wait while we carefully engrave it onto your selected jewellery. You can choose to have it shipped to you or collect it in person.",
          alt: "Add print",
        },
        step3: {
          title: "Receive Your Jewellery",
          text: "Once your piece is ready, we will carefully package and ship it to you — or you can pick it up from our store. Your personalized jewellery is now ready to be worn and treasured.",
          alt: "Take your jewellery",
        },
      },

      productsTitle: "Personalized products",
      productsTitleLine1: "Personalized",
      productsTitleLine2: "products",
      howItWorks: "How it works",
      readyTitle: "Are You Ready?",
    },

    admin: {
      ordersTitle: "Admin orders",
      productsTitle: "Admin products",
      resetFilters: "Reset filters",
      noOrdersFound: "No matching orders found.",
      addProduct: "Add product",
      deleting: "Deleting...",
      deleteSelected: "Delete selected",
      searchByNameOrId: "Search by name or id",
      searchByEmail: "Search by email",
      allCategories: "All categories",
      allDeliveryMethods: "All delivery methods",
      allStatuses: "All statuses",
      newestFirst: "Newest first",
      oldestFirst: "Oldest first",
      priceLowToHigh: "Price: low to high",
      priceHighToLow: "Price: high to low",
      rings: "Rings",
      earrings: "Earrings",
      necklaces: "Necklaces",
      bracelets: "Bracelets",
      personal: "Personal",
      totalOrders: "Total orders",
      totalRevenue: "Total revenue",
      pending: "Pending",
      confirmed: "Confirmed",
      shipped: "Shipped",
      completed: "Completed",
      canceled: "Canceled",
      orderId: "Order ID",
      date: "Date",
      image: "Image",
      email: "Email",
      items: "Items",
      delivery: "Delivery",
      total: "Total",
      status: "Status",
      details: "Details",
      name: "Name",
      category: "Category",
      price: "Price",
      stock: "Stock",
      bestSeller: "Best seller",
      created: "Created",
      edit: "Edit",
      delete: "Delete",
      yes: "Yes",
      no: "No",
      close: "Close",
      customer: "Customer",
      pickupLabel: "Pickup",
      shippingLabel: "Shipping",
      type: "Type:",
      location: "Location:",
      method: "Method:",
      payment: "Payment:",
      fee: "Fee:",
      totalLabel: "Total:",
      statusControl: "Status Control",
      canceledNote: "This order is canceled. Stock has already been restored and cannot be reopened.",
      orderItems: "Order Items",
      quantity: "Quantity:",
      color: "Color:",
      size: "Size:",
      service: "Service:",
      shippingKitService: "Shipping kit (+15€)",
      inStoreService: "In-store",
      standardService: "Standard",
      vilniusSalon: "Vilnius salon",
      kaunasSalon: "Kaunas salon",
      card: "Card",
      page: "Page",
      ordersOnPage: "order(s) on this page",
      showing: "Showing",
      of: "of",
      orders: "orders",
      filteredProducts: "filtered products",
      selected: "Selected:",
    },
  },

  lt: {
    thankYou: "Ačiū!",
    subscriptionSuccess: "Sėkmingai užsiprenumeravote mūsų naujienlaiškį.",
    collections: "Kolekcijos",
    aboutUs: "Apie mus",
    contacts: "Kontaktai",
    wishlist: "Patikusios",
    bag: "Krepšelis",
    logIn: "Prisijungti",
    close: "Uždaryti",
    closeBag: "Uždaryti krepšelį",
    account: "Paskyra",
    subscribeTitle: "Prenumeruokite ir sutaupykite",
    subscribeText:
      "Prenumeruokite mūsų naujienlaiškį el. paštu ir gaukite geriausius pasiūlymus bei nuolaidas",
    emailPlaceholder: "El. paštas",
    subscribeButton: "Prenumeruoti",
    home: "Pagrindinis",
    products: "Produktai",
    favorites: "Patikusios",
    bagEmpty: "Jūsų krepšelis tuščias.",
    soldOut: "Išparduota",
    inStock: "Liko",
    shippingKit: "Siuntimo rinkinys",
    serviceOption: "Paslaugos pasirinkimas",
    inStore: "Salone",
    color: "Spalva",
    size: "Dydis",
    oneSize: "Vienas dydis",
    decreaseQuantity: "Sumažinti kiekį",
    increaseQuantity: "Padidinti kiekį",
    removeItem: "Pašalinti prekę",
    checkout: "Apmokėti",
    warranty: "2 metų garantija",
    twoYearWarranty: "2 metų garantija",
    highQuality: "Aukšta kokybė",
    fastDelivery: "Greitas pristatymas",
    return90Days: "90 dienų grąžinimas",
    ninetyDayReturn: "90 dienų grąžinimas",
    bestSellers: "Perkamiausi",
    seeAll: "Žiūrėti visus",
    seeAllBestSellers: "Žiūrėti visus perkamiausius",
    categories: "Kategorijos",
    heroTitleLine1: "Atraskite",
    heroTitleLine2: "Nesenstančią",
    heroTitleLine3: "Eleganciją",
    heroTitleDesktop: "Atraskite nesenstančią eleganciją",
    previous: "Ankstesnis",
    next: "Kitas",
    noItemsAvailable: "Šiuo metu prekių nėra.",
    newCollection: "Nauja kolekcija",
    newCollectionLine1: "Nauja",
    newCollectionLine2: "kolekcija",
    shopNow: "Pirkti",
    shopNewCollection: "Pirkti naują kolekciją",
    personalizedJewellery: "Personalizuoti papuošalai",
    personalizedLine1: "Personalizuoti",
    personalizedLine2: "papuošalai",
    shopPersonalizedJewellery: "Pirkti personalizuotus papuošalus",
    filter: "Filtrai",
    closeFilter: "Uždaryti filtrus",
    material: "Medžiaga",
    price: "Kaina",
    appearance: "Išvaizda",
    gemstones: "Brangakmeniai",
    to: "iki",
    sortBy: "Rūšiuoti pagal:",
    closeSort: "Uždaryti rūšiavimą",
    sortPriceHighToLow: "Kaina, nuo didžiausios",
    sortPriceLowToHigh: "Kaina, nuo mažiausios",
    sortBestSelling: "Perkamiausi",
    sortDateOldToNew: "Data, nuo seniausių",
    sortDateNewToOld: "Data, nuo naujausių",
    selectCategory: "Pasirinkti kategoriją",
    testimonialsTitle: "Ką žmonės\nsako apie mus",
    testimonials: {
      "jessica-shy": "Minimalūs, bet su charakteriu. Atrodo prabangiai, o ant odos – lengvi kaip oras.",
      "tomas-narkevicius": "Modernus dizainas be pertekliaus. Nešioju dažnai – visada sulaukia dėmesio.",
      "angelou": "Labai elegantiški papuošalai. Puikiai papildo net paprasčiausią įvaizdį.",
      "fc-baseball": "Stilinga, kokybiška ir išskirtinė. Puikus pasirinkimas tiek dovanai, tiek sau.",
      "donatas-montvydas": "Papuošalai, kurie tinka tiek scenai, tiek kasdienai.",
      "monika-liu": "Subtilu, estetiška ir labai jauku. Jaučiasi rankų darbas ir dėmesys detalėms.",
    },
    productNames: {
      // Static data (bestSellers.js) - with quotes and lowercase
      '"Earth" ring': '„Žemė" žiedas',
      '"Cut" ring': '„Cut" žiedas',
      '"Dot" necklace': '„Dot" vėrinys',
      '"Echo" rings': '„Echo" žiedai',
      '"Fold" ring': '„Fold" žiedas',
      '"Fluid" ring': '„Fluid" žiedas',
      '"Still" ring': '„Still" žiedas',
      '"Um" ring': '„Um" žiedas',
      '"Pure" earrings': '„Pure" auskarai',
      '"Bond" bracelet': '„Bond" apyrankė',
      // Database products - Title Case
      "Fluid Ring": "„Fluid" žiedas",
      "Still Ring": "„Still" žiedas",
      "Fold Ring": "„Fold" žiedas",
      "Um Ring": "„Um" žiedas",
      "Earth Ring": "„Žemė" žiedas",
      "Cut Ring": "„Cut" žiedas",
      "Dot Necklace": "„Dot" vėrinys",
      "Echo Rings": "„Echo" žiedai",
      "Pure Earrings": "„Pure" auskarai",
      "Bond Bracelet": "„Bond" apyrankė",
    },
    add: "Pridėti",
    remove: "Pašalinti",
    toCart: "į krepšelį",
    toFavorites: "į patikusias",
    fromFavorites: "iš patikusių",
    toBag: "į krepšelį",
    open: "Atidaryti",
    hover: "užvedus",
    productImage: "Papuošalo nuotrauka",
    aboutStudioText:
      "Kiekvienas mūsų papuošalas kuriamas tam, kad perteiktų jausmą — meilę, grožį ir nesenstančią eleganciją. Kruopščiai pagamintas iš aukščiausios kokybės medžiagų, kiekvienas dizainas skirtas būti branginamas. Čia prabanga tampa jūsų istorijos dalimi.",
    aboutStudioImageAlt: "Apie mūsų studiją",
    studioLogoAlt: "Studijos logotipas",
    addToBag: "Į krepšelį",
    clearAll: "Išvalyti viską",
    pagination: "Puslapiavimas",
    previousPage: "Ankstesnis puslapis",
    nextPage: "Kitas puslapis",
    page: "Puslapis",
    umStudioLogo: "UM Studio",
    subscribeAndSave: "Prenumeruokite ir sutaupykite",
    subscribeBannerText:
      "Prenumeruokite mūsų naujienlaiškį el. paštu ir gaukite geriausius pasiūlymus bei nuolaidas",
    subscribe: "Prenumeruoti",
    subscribeBannerImageAlt: "Prenumeratos reklamjuostė",
    rings: "Žiedai",
    necklaces: "Kaklo papuošalai",
    bracelets: "Apyrankės",
    earrings: "Auskarai",
    personal: "Personalizuoti",

    withGem: "Su brangakmeniu",
    withoutGem: "Be brangakmenio",
    rough: "Grublėtas",
    smoothSurface: "Lygus paviršius",

    kristolas: "Kristolas",
    cirkonis: "Cirkonis",
    deimantas: "Deimantas",
    perlas: "Perlas",

    silver: "Sidabras",
    gold: "Auksas",
    softBlue: "Švelni mėlyna",
    softGreen: "Švelni žalia",
    softYellow: "Švelni geltona",

    loading: "Kraunama...",
    noProductsFound: "Produktų nerasta.",
    showing: "Rodoma",
    of: "iš",

    phone: "Telefonas",
    name: "Vardas",
    enterYourName: "Įveskite savo vardą",
    enterYourEmail: "Įveskite savo el. paštą",
    phoneNumber: "Telefono numeris",
    enterYourPhoneNumber: "Įveskite savo telefono numerį",
    yourMessage: "Jūsų žinutė",
    enterMessage: "Įveskite žinutę",
    sendMessage: "Siųsti žinutę",
    yourMessageSentSuccessfully: "Jūsų žinutė sėkmingai išsiųsta",
    messageSent: "Žinutė išsiųsta",
    pleaseFillInThisField: "Užpildykite šį lauką.",
    enterValidEmailAddress: "Įveskite galiojantį el. pašto adresą.",

    myFavourites: "Mano mėgstamiausi",
    noFavouriteItemsYet: "Dar neturite mėgstamų prekių.",

    hidePassword: "Slėpti slaptažodį",
    showPassword: "Rodyti slaptažodį",
    thisFieldIsRequired: "Šis laukas yra privalomas.",
    passwordsDoNotMatch: "Slaptažodžiai nesutampa.",
    somethingWentWrong: "Kažkas nepavyko.",

    signIn: "Prisijungti",
    createAccount: "Sukurti paskyrą",
    invalidCredentials: "Neteisingas el. pašto adresas arba slaptažodis.",
    emailAlreadyInUse: "Vartotojas su šiuo el. pašto adresu jau egzistuoja.",
    pleaseWait: "Prašome palaukti...",
    firstName: "Vardas",
    lastName: "Pavardė",
    emailAddress: "El. pašto adresas",
    password: "Slaptažodis",
    confirmPassword: "Patvirtinkite slaptažodį",
    forgotPassword: "Pamiršote slaptažodį?",

    pageNotFound: "Puslapis nerastas",
    thisPageDoesNotExist: "Šis puslapis neegzistuoja.",
    notFoundText:
      "Puslapis, kurio ieškote, galėjo būti perkeltas, pašalintas arba nuoroda yra neteisinga.",
    backToHome: "Grįžti į pradžią",
    viewCollections: "Peržiūrėti kolekcijas",
    discoverJewelryThatStays:
      "Atraskite papuošalus, kurie tampa jūsų istorijos dalimi.",
    notFoundSideText:
      "Peržiūrėkite mūsų kolekcijas ir raskite nesenstančius papuošalus, skirtus nešioti, dovanoti ir branginti.",

    bestSellersIntroDescription:
      "Kiekvienas mūsų papuošalas kuriamas tam, kad perteiktų jausmą — meilę, grožį ir nesenstančią eleganciją. Kruopščiai pagamintas iš aukščiausios kokybės medžiagų, kiekvienas dizainas skirtas būti branginamas.",
    personalizedJewelry: "Personalizuoti papuošalai",

    ourSalons: "Mūsų salonai",
    salon: "salonas",
    workingHours: "I–VII — 10:00–20:00",

    exploreOurProducts: "Atraskite mūsų produktus",
    personalizedProducts: "Personalizuoti produktai",

    orderHistory: "Užsakymų istorija",
    profile: "Profilis",
    logOut: "Atsijungti",

    changePassword: "Keisti slaptažodį",
    back: "Atgal",
    currentPassword: "Dabartinis slaptažodis",
    newPassword: "Naujas slaptažodis",
    repeatNewPassword: "Pakartokite naują slaptažodį",
    saving: "Saugoma...",
    save: "Išsaugoti",
    passwordUpdatedSuccessfully: "Slaptažodis sėkmingai atnaujintas.",
    passwordMustBeAtLeast: "Slaptažodis turi būti bent",
    characters: "simbolių",

    openOrder: "Atidaryti užsakymą",
    more: "daugiau",
    orderNo: "Užsakymo nr.",

    loadingOrders: "Kraunami užsakymai...",
    noOrdersYet: "Užsakymų dar nėra.",
    failedToLoadOrders: "Nepavyko užkrauti užsakymų.",
    pickup: "Atsiėmimas",
    omniva: "Omniva",
    lpExpress: "LP Express",

    pending: "Laukiama",
    confirmed: "Patvirtintas",
    shipped: "Išsiųstas",
    completed: "Įvykdytas",
    canceled: "Atšauktas",

    orderDate: "Užsakymo data",
    deliveryTo: "Pristatyti į",
    billingAddress: "Atsiskaitymo adresas",
    service: "Paslauga",
    delivery: "Pristatymas",
    carrier: "Vežėjas",
    deliveryPrice: "Pristatymo kaina",
    total: "Iš viso",
    shippingKitWithPrice: "Siuntimo rinkinys (+15€)",

    requiredShort: "Privaloma.",
    savedSuccessfully: "Sėkmingai išsaugota.",
    enterYourFirstName: "Įveskite savo vardą",
    enterYourLastName: "Įveskite savo pavardę",
    change: "Keisti",

    pleaseChooseServiceOption: "Pasirinkite paslaugos variantą.",
    productNotFound: "Produktas nerastas.",
    invalidProductUrl: "Neteisinga produkto nuoroda.",
    backToCollections: "Grįžti į kolekcijas",

    selectedVariantSoldOut: "Pasirinktas variantas išparduotas",
    removeFromWishlist: "Pašalinti iš mėgstamų",
    addToWishlist: "Pridėti į mėgstamus",
    dimensionsAndDetails: "Išmatavimai ir detalės",
    personalJewelleryHowItWorks: "Personalizuoti papuošalai - kaip tai veikia",
    quantity: "Kiekis",
    orderValue: "Užsakymo vertė",

    product: {
      label: "Produktas",

      youMayAlsoLike: {
        titleLine1: "Jums gali",
        titleLine2: "taip pat patikti",
        seeAll: "Žiūrėti visus",
        seeAllAriaLabel: "Žiūrėti visus produktus",
      },

      detailsPanel: {
        title: "Išmatavimai ir detalės",
        close: "Uždaryti",
        closeAriaLabel: "Uždaryti detales",
        adjustableFromToPrefix: "reguliuojamas nuo",
        adjustableFromToMiddle: "iki",
        sectionTitles: {
          dimensions: "Išmatavimai:",
        },
        labels: {
          metal: "Metalas - ",
          bandWidth: "Žiedo plotis: ",
          weight: "Svoris: ",
          gemstone: "Akmuo: ",
          productCode: "Produkto kodas: ",
          chain: "Grandinėlė - ",
          totalNecklaceLength: "Bendras vėrinio ilgis: ",
          height: "Aukštis: ",
          width: "Plotis: ",
          size: "Dydis - ",
          totalBraceletLength: "Bendras apyrankės ilgis: ",
        },
        metals: {
          softYellow: "Švelni geltona",
          softBlue: "Švelni mėlyna",
          softGreen: "Švelni žalia",
          gold: "Auksas",
          silver: "Sidabras",
        },
        defaultTexts: {
          rings:
            "Šis platesnis žiedas pasižymi tekstūruotu paviršiumi, įkvėptu organiškų formų, kuris sukuria subtilų šviesos ir gylio žaismą. Ryškų siluetą subalansuoja išbaigta apdaila, todėl papuošalas atrodo moderniai ir kartu išlieka laikui nepavaldus. Nešiojamas vienas kaip akcentas arba derinamas su minimalistiniais papuošalais, šis žiedas suteikia įvaizdžiui lengvos elegancijos.",
          bracelets:
            "Ši išraiškinga grandinėlės tipo apyrankė sukurta iš tarpusavyje sujungtų, poliruotų žiedų, kurie formuoja tvirtą, bet harmoningą siluetą. Lygios, apvalintos grandys gražiai atspindi šviesą ir suteikia papuošalui rafinuotą, šiuolaikišką pojūtį. Nešiojama viena arba lengvai derinama su kitais papuošalais, ši apyrankė tampa moderniu akcentu tiek kasdieniams, tiek puošnesniems deriniams.",
          necklaces:
            "Šis subtilus vėrinys turi ploną grandinėlę, papildytą elegantišku lašo formos pakabuku, kuris dailiai gula išilgai kaklo linijos. Minimalistinis dizainas išryškina švarias linijas ir lengvą judesį, sukurdamas elegantišką, pailgintą siluetą. Tinkamas sluoksniuoti arba nešioti vienas, šis papuošalas suteikia rafinuotą, modernų akcentą tiek kasdieniams, tiek vakariniams deriniams.",
          earrings:
            "Šie minimalistiniai auskarai pasižymi švelniai išgaubta trikampio forma ir lygiu, šukuotu paviršiumi, kuris subtiliai bei elegantiškai atspindi šviesą. Skulptūriškas siluetas suteikia modernumo, bet kartu išlieka laikui nepavaldus ir lengvai pritaikomas. Jie puikiai dera tiek prie kasdienių, tiek prie puošnesnių derinių ir yra universali papuošalų kolekcijos dalis.",
        },
      },
    },

    checkoutThankYou: {
      title: "Ačiū, kad apsipirkote!",
      imageAlt: "Ačiū",
      orderIdLabel: "Užsakymo ID",
      confirmationEmailLabel: "Patvirtinimo el. paštas",
      backToShopping: "Grįžti apsipirkti",
      shippingMessage:
        "Jūsų užsakymas sėkmingai gautas. Netrukus atsiųsime užsakymo informaciją ir pristatymo atnaujinimus į jūsų el. paštą.",
      pickupMessage:
        "Jūsų užsakymas sėkmingai gautas. Susisieksime su jumis el. paštu, kai jis bus paruoštas atsiėmimui {pickupLocation}.",
      pickupLocations: {
        vilnius: "Vilniaus salone",
        kaunas: "Kauno salone",
        default: "mūsų salone",
      },
    },

    checkoutPage: {
      processing: "Apdorojama...",
      payNow: "Mokėti dabar",
      paymentSuccess: "Mokėjimas sėkmingas",
      backToCheckout: "Grįžti į apmokėjimą",
      contactTitle: "Kontaktai",
      emailLabel: "El. pašto adresas",
      emailPlaceholder: "Įveskite savo el. paštą",
      deliveryInformation: "Pristatymo informacija",
      ship: "Siuntimas",
      pickup: "Atsiėmimas",
      orderSummary: "Užsakymo santrauka",
      quantityShort: "Kiekis",
      subtotal: "Tarpinė suma",
      free: "Nemokamai",
      paymentTitle: "Mokėjimas",
      creditCard: "Mokėjimo kortelė",
      cardNumberLabel: "Kortelės numeris",
      cardNumberPlaceholder: "1234 1234 1234 1234",
      cardDateLabel: "Data",
      cardDatePlaceholder: "MM/YY",
      cardCvcLabel: "CVC",
      cardCvcPlaceholder: "CVC",
      cardOwnerNameLabel: "Kortelės savininko vardas, pavardė",
      cardOwnerNamePlaceholder: "Pilnas vardas",
      bankPayment: "El. bankininkystė",
      chooseYourBank: "Pasirinkite savo banką",
      bankRedirectText:
        "Paspaudę „Mokėti dabar“ būsite nukreipti į pasirinktą banką.",
      pickupTitle: "Atsiėmimo vieta",
      pickupDescription:
        "Pasirinkite saloną, kuriame norite atsiimti užsakymą.",
      pickupLocations: {
        vilnius: "Vilniaus salonas",
        kaunas: "Kauno salonas",
      },
      pickupAddresses: {
        vilnius: "Kauno g. 24",
        kaunas: "Žemaičių g. 24",
      },

      pickupInfo:
        "Atsiėmimas yra nemokamas. Po užsakymo susisieksime su jumis el. paštu.",
      countryRegionLabel: "Šalis / regionas",
      countryLithuania: "Lietuva",
      addressLabel: "Adresas",
      apartmentLabel: "Butas, numeris ir kt.",
      optionalPlaceholder: "(nebūtina)",
      cityLabel: "Miestas",
      postalCodeLabel: "Pašto kodas",

      chooseDeliveryMethod: "Pasirinkite pristatymo būdą",
      lpDelivery: "LP EXPRESS pristatymas į namus",
      omnivaDelivery: "Omniva pristatymas į namus",

      errors: {
        enterValidEmail: "Įveskite galiojantį el. pašto adresą.",
        firstNameRequired: "Vardas yra privalomas.",
        lastNameRequired: "Pavardė yra privaloma.",
        addressRequired: "Adresas yra privalomas.",
        cityRequired: "Miestas yra privalomas.",
        postalCodeRequired: "Pašto kodas yra privalomas.",
        phoneRequired: "Telefono numeris yra privalomas.",
        invalidCardNumber: "Neteisingas kortelės numeris.",
        useCardDateFormat: "Naudokite MM/YY formatą.",
        invalidCvc: "Neteisingas CVC.",
        cardOwnerNameRequired: "Kortelės savininko vardas yra privalomas.",
        productNoLongerExists: 'Produktas "{productName}" nebeegzistuoja.',
        productSoldOut: 'Produktas "{productName}" yra išparduotas.',
        notEnoughStock:
          'Liko tik {stockQuantity} vnt. produkto "{productName}", bet jūsų krepšelyje yra {qty}.',
      },
    },

    personalized: {
      steps: {
        step1: {
          title: "Pasirinkite papuošalą",
          text: "Pasirinkite norimą papuošalą iš mūsų žiedų ir kaklo papuošalų kolekcijos. Pasirinkite medžiagą — auksą arba sidabrą — ir tinkamiausią dydį.",
          alt: "Pasirinkti papuošalą",
        },
        step2: {
          title: "Pridėkite savo asmeninį prisilietimą",
          shippingTitle: "Siuntimo variantas:",
          shippingText:
            "Užbaikite užsakymą ir mes atsiųsime jums rinkinį, skirtą atspaudo paėmimui, kurį norėsite išgraviruoti ant papuošalo. Paruošę, išsiųskite jį mums atgal ir mes pradėsime kurti jūsų personalizuotą papuošalą.",
          inStoreTitle: "Salone:",
          inStoreText:
            "Apsilankykite mūsų salone ir mes paimsime atspaudą vietoje. Po to belieka palaukti, kol kruopščiai išgraviruosime jį ant pasirinkto papuošalo. Galėsite pasirinkti pristatymą arba atsiimti vietoje.",
          alt: "Pridėti atspaudą",
        },
        step3: {
          title: "Gaukite savo papuošalą",
          text: "Kai jūsų papuošalas bus paruoštas, jį kruopščiai supakuosime ir išsiųsime — arba galėsite atsiimti mūsų salone. Jūsų personalizuotas papuošalas paruoštas nešioti ir saugoti.",
          alt: "Gauti papuošalą",
        },
      },

      productsTitle: "Personalizuoti produktai",
      productsTitleLine1: "Personalizuoti",
      productsTitleLine2: "produktai",
      howItWorks: "Kaip tai veikia",
      readyTitle: "Ar esi pasiruošęs?",
    },

    admin: {
      ordersTitle: "Užsakymų administravimas",
      productsTitle: "Produktų administravimas",
      resetFilters: "Atstatyti filtrus",
      noOrdersFound: "Atitinkančių užsakymų nerasta.",
      addProduct: "Pridėti produktą",
      deleting: "Trinama...",
      deleteSelected: "Ištrinti pasirinktus",
      searchByNameOrId: "Ieškoti pagal pavadinimą arba ID",
      searchByEmail: "Ieškoti pagal el. paštą",
      allCategories: "Visos kategorijos",
      allDeliveryMethods: "Visi pristatymo būdai",
      allStatuses: "Visi statusai",
      newestFirst: "Naujausi pirmiausia",
      oldestFirst: "Seniausi pirmiausia",
      priceLowToHigh: "Kaina: nuo mažiausios",
      priceHighToLow: "Kaina: nuo didžiausios",
      rings: "Žiedai",
      earrings: "Auskarai",
      necklaces: "Karoliai",
      bracelets: "Apyrankės",
      personal: "Personalizuoti",
      totalOrders: "Visi užsakymai",
      totalRevenue: "Bendros pajamos",
      pending: "Laukiantys",
      confirmed: "Patvirtinti",
      shipped: "Išsiųsti",
      completed: "Užbaigti",
      canceled: "Atšaukti",
      orderId: "Užsakymo ID",
      date: "Data",
      image: "Nuotrauka",
      email: "El. paštas",
      items: "Prekės",
      delivery: "Pristatymas",
      total: "Suma",
      status: "Statusas",
      details: "Detalės",
      name: "Pavadinimas",
      category: "Kategorija",
      price: "Kaina",
      stock: "Sandėlis",
      bestSeller: "Populiariausias",
      created: "Sukurta",
      edit: "Redaguoti",
      delete: "Ištrinti",
      yes: "Taip",
      no: "Ne",
      close: "Uždaryti",
      customer: "Klientas",
      pickupLabel: "Atsiėmimas",
      shippingLabel: "Siuntimas",
      type: "Tipas:",
      location: "Vieta:",
      method: "Metodas:",
      payment: "Mokėjimas:",
      fee: "Mokestis:",
      totalLabel: "Suma:",
      statusControl: "Statuso valdymas",
      canceledNote: "Šis užsakymas atšauktas. Sandėlio kiekis jau atstatytas ir užsakymo atidaryti nebegalima.",
      orderItems: "Užsakymo prekės",
      quantity: "Kiekis:",
      color: "Spalva:",
      size: "Dydis:",
      service: "Paslauga:",
      shippingKitService: "Siuntimo rinkinys (+15€)",
      inStoreService: "Salone",
      standardService: "Standartinis",
      vilniusSalon: "Vilniaus salonas",
      kaunasSalon: "Kauno salonas",
      card: "Kortelė",
      page: "Puslapis",
      ordersOnPage: "užsakymas(-ai) šiame puslapyje",
      showing: "Rodoma",
      of: "iš",
      orders: "užsakymų",
      filteredProducts: "filtruotų produktų",
      selected: "Pasirinkta:",
    },
  },
};

const allowedLanguages = ["en", "lt"];

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const savedLang = localStorage.getItem("lang");
    return allowedLanguages.includes(savedLang) ? savedLang : "en";
  });

  useEffect(() => {
    localStorage.setItem("lang", lang);
  }, [lang]);

  const value = useMemo(() => {
    return {
      lang,
      setLang,
      t: translations[lang] || translations.en,
    };
  }, [lang]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
